<template>
    <div>
        <div class="col-md-8 offset-md-2 mt-5">
            <div>
                <h4>Users</h4>
            </div>
            <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Post One</td>
                    <td>Web Development</td>
                    <td>May 10 2018</td>
                    <td>
                    <a href="details.html" class="btn btn-secondary">
                        <i class="fas fa-angle-double-right"></i> Details
                    </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>   
    </div>
</template>